[versions]
gradle = "7.4.0-alpha08"
kotlin = "1.7.10"
kotlin-ksp = "1.7.10-1.0.6"
gms = "4.3.10"
crashlytics = "2.8.1"
dagger = "2.43"
desugaring = "1.1.5"
coroutines = "1.6.1"

compose = "1.2.0-rc03"
compose-compiler = "1.3.0-beta01"
compose-constraintLayout = "1.0.1"
compose-accompanist = "0.24.13-rc"
compose-landscapist = "1.5.3"

androidx-core = "1.8.0"
androidx-legacy = "1.0.0"
androidx-appcompat = "1.4.1"
androidx-media = "1.6.0"
androidx-recycler = "1.2.1"
androidx-browser = "1.4.0"
androidx-material = "1.6.0"
androidx-preference = "1.2.0"
androidx-palette = "1.0.0"
androidx-annotations = "1.4.0"
androidx-coordinator = "1.2.0"
androidx-fragments = "1.5.0"
androidx-activity = "1.5.0"
androidx-lifecycle = "2.5.0"
androidx-constraintLayout = "2.1.4"

ui-glide = "4.13.2"
ui-lottie = "3.4.2"
ui-materialDialogs = "3.3.0"
ui-scrollHelper = "1.2.1"
ui-blurKit = "1.0.0"
ui-colorDesaturation = "1.0.2"
ui-tapTargetView = "2.0.0"

data-sqlContentResolver = "1.2.1"
data-room = "2.4.2"
data-okhttp = "4.8.1"
data-retrofit = "2.9.0"
data-gson = "2.8.6"
data-lastFmBinding = "0.1.2"

firebase-core = "21.0.0"
firebase-crashlytics = "18.2.10"

utils-aes = "1.1.0"
utils-fuzzy = "1.2.0"
utils-leakCanary = "2.9.1"

test-junit = "4.13"
test-mockito = "3.5.10"
test-mockito-kotlin = "2.2.0"
test-robolectric = "4.8.1"
test-flowAssertions = "1.6.2"

[libraries]
plugin-gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-kotlin-ksp = { module = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin", version.ref = "kotlin-ksp" }
plugin-gms = { module = "com.google.gms:google-services", version.ref = "gms" }
plugin-crashlytics = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "crashlytics" }
plugin-hilt = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "dagger" }

desugaring = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugaring" }

kotlin = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

hilt-core = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger" }
hilt-test = { module = "com.google.dagger:hilt-android-testing", version.ref = "dagger" }

androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-legacy = { module = "androidx.legacy:legacy-support-v4", version.ref = "androidx-legacy" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-media = { module = "androidx.media:media", version.ref = "androidx-media" }
androidx-recycler = { module = "androidx.recyclerview:recyclerview", version.ref = "androidx-recycler" }
androidx-browser = { module = "androidx.browser:browser", version.ref = "androidx-browser" }
androidx-material = { module = "com.google.android.material:material", version.ref = "androidx-material" }
androidx-preference = { module = "androidx.preference:preference", version.ref = "androidx-preference" }
androidx-palette = { module = "androidx.palette:palette", version.ref = "androidx-palette" }
androidx-annotations = { module = "androidx.annotation:annotation", version.ref = "androidx-annotations" }
androidx-constraintLayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-constraintLayout" }
androidx-fragments = { module = "androidx.fragment:fragment-ktx", version.ref = "androidx-fragments" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-java8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "androidx-lifecycle" }
androidx-lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-service = { module = "androidx.lifecycle:lifecycle-service", version.ref = "androidx-lifecycle" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "androidx-lifecycle" }

compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
compose-icons = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
compose-constraintLayout = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "compose-constraintLayout" }
compose-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "compose-accompanist" }
compose-pager-indicator = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "compose-accompanist" }
compose-landscapist = { module = "com.github.skydoves:landscapist-glide", version.ref = "compose-landscapist" }

ui-glide = { module = "com.github.bumptech.glide:glide", version.ref = "ui-glide" }
ui-glide-processor = { module = "com.github.bumptech.glide:compiler", version.ref = "ui-glide" }
ui-scrollHelper = { module = "com.github.ologe:scroll-helper", version.ref = "ui-scrollHelper" }
ui-blurKit = { module = "io.alterac.blurkit:blurkit", version.ref = "ui-blurKit" }
ui-lottie = { module = "com.airbnb.android:lottie", version.ref = "ui-lottie" }
ui-dialogs-core = { module = "com.afollestad.material-dialogs:core", version.ref = "ui-materialDialogs" }
ui-dialogs-color = { module = "com.afollestad.material-dialogs:color", version.ref = "ui-materialDialogs" }
ui-colorDesaturation = { module = "com.github.ologe:color-desaturation", version.ref = "ui-colorDesaturation" }
ui-tapTargetView = { module = "com.github.ologe:taptargetview", version.ref = "ui-tapTargetView" }

data-sqlContentResolver = { module = "com.github.ologe:android-content-resolver-SQL", version.ref = "data-sqlContentResolver" }
data-room = { module = "androidx.room:room-runtime", version.ref = "data-room" }
data-room-ktx = { module = "androidx.room:room-ktx", version.ref = "data-room" }
data-room-processor = { module = "androidx.room:room-compiler", version.ref = "data-room" }
data-room-testing = { module = "androidx.room:room-testing", version.ref = "data-room" }
data-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "data-okhttp" }
data-okhttp-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "data-okhttp" }
data-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "data-retrofit" }
data-retrofit-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "data-retrofit" }
data-gson = { module = "com.google.code.gson:gson", version.ref = "data-gson" }
data-lastFmBinding = { module = "de.u-mass:lastfm-java", version.ref = "data-lastFmBinding" }

firebase-core = { module = "com.google.firebase:firebase-core", version.ref = "firebase-core" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics", version.ref = "firebase-crashlytics" }

utils-aes = { module = "com.github.tozny:java-aes-crypto", version.ref = "utils-aes" }
utils-fuzzy = { module = "me.xdrop:fuzzywuzzy", version.ref = "utils-fuzzy" }
utils-leakCanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "utils-leakCanary" }

test-junit = { module = "junit:junit", version.ref = "test-junit" }
test-mockito = { module = "org.mockito:mockito-inline", version.ref = "test-mockito" }
test-mockito-kotlin = { module = "com.nhaarman.mockitokotlin2:mockito-kotlin", version.ref = "test-mockito-kotlin" }
test-robolectric = { module = "org.robolectric:robolectric", version.ref = "test-robolectric" }
test-flowAssertions = { module = "com.github.ologe:flow-test-observer", version.ref = "test-flowAssertions" }